apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy

spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 2
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: vinsdocker/k8s-app:v1
          ports:
        - name: "app-port"
          containerPort: 80