apiVersion: v1
kind: Pod
metadata:
  name: webserver-prometheus
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: prometheus
    image: prom/prometheus:v2.30.3
    ports:
    - containerPort: 9090
    args:
    - --config.file=/etc/prometheus/prometheus.yml
    volumeMounts:
    - name: prometheus-config
      mountPath: /etc/prometheus
  volumes:
  - name: prometheus-config
    configMap:
      name: prometheus-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |
    # Place your Prometheus configuration here
    # Example:
    scrape_configs:
    - job_name: 'my-service'
      static_configs:
      - targets: ['localhost:8080']
