apiVersion: v1
kind: Secret
metadata:
  name: mysecret
 
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW5AMTIzNDU2Nw==

---
apiVersion: v1
kind: Pod
metadata:
  name: "my-pod"
  
  labels:
    app: "my-pod"
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    envFrom: 
    - secretRef: 
        name: mysecret
    args:
    - env
