apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: myapp-rs
spec:
  selector:
    matchLabels:
      team: team-a
  replicas: 2
  template:
    metadata:
      labels:
        team: team-a
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2