apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: nginx:1.14.2
        ports:
        - name: web
          containerPort:  80
          protocol: TCP
        